name: Build, test and publish

on:
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Fetch repository
      run: git fetch --prune --unshallow
  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
          versionSpec: '5.x'
    
    - name: Use GitVersion
      id: gitversion  # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.9
      
    - name: Output version values 
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.SemVer }}"
        mkdir -p ./build
        touch ./build/gitversion.semver.txt
        echo "${{ steps.gitversion.outputs.SemVer }}" >> ./build/gitversion.semver.txt
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
        
    - name: Build QuantitativeWorld
      run: dotnet build ./src/QuantitativeWorld/QuantitativeWorld.csproj --configuration Release --framework netstandard2.0 --output ../../build /p:Version=${{ steps.gitversion.outputs.SemVer }}
      
    - name: Build QuantitativeWorld.Text
      run: dotnet build ./src/QuantitativeWorld.Text/QuantitativeWorld.Text.csproj --configuration Release --framework netstandard2.0 --output ../../build /p:Version=${{ steps.gitversion.outputs.SemVer }}
      
    - name: Build QuantitativeWorld.Text.Json
      run: dotnet build ./src/QuantitativeWorld.Text.Json/QuantitativeWorld.Text.Json.csproj --configuration Release --framework netstandard2.0 --output ../../build /p:Version=${{ steps.gitversion.outputs.SemVer }}
        
    - name: Build QuantitativeWorld.FluentAssertions
      run: dotnet build ./src/QuantitativeWorld/QuantitativeWorld.FluentAssertions.csproj --configuration Release --framework netstandard2.0 --output ../../build /p:Version=${{ steps.gitversion.outputs.SemVer }}
        
    - name: Build DecimalQuantitativeWorld
      run: dotnet build ./src/QuantitativeWorld/DecimalQuantitativeWorld.csproj --configuration Release --framework netstandard2.0 --output ../../build /p:Version=${{ steps.gitversion.outputs.SemVer }}
      
    - name: Build DecimalQuantitativeWorld.Text
      run: dotnet build ./src/QuantitativeWorld.Text/DecimalQuantitativeWorld.Text.csproj --configuration Release --framework netstandard2.0 --output ../../build /p:Version=${{ steps.gitversion.outputs.SemVer }}
      
    - name: Build DecimalQuantitativeWorld.Text.Json
      run: dotnet build ./src/QuantitativeWorld.Text.Json/DecimalQuantitativeWorld.Text.Json.csproj --configuration Release --framework netstandard2.0 --output ../../build /p:Version=${{ steps.gitversion.outputs.SemVer }}
        
    - name: Build DecimalQuantitativeWorld.FluentAssertions
      run: dotnet build ./src/QuantitativeWorld/DecimalQuantitativeWorld.FluentAssertions.csproj --configuration Release --framework netstandard2.0 --output ../../build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./build
      
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Fetch repository
      run: git fetch --prune
          
    - name: Test QuantitativeWorld
      run: dotnet test ./src/QuantitativeWorld.Tests/QuantitativeWorld.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=QuantitativeWorld.TestsResults.trx"
      
    - name: Test QuantitativeWorld.Text
      run: dotnet test ./src/QuantitativeWorld.Text.Tests/QuantitativeWorld.Text.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=QuantitativeWorld.Text.TestsResults.trx"
      
    - name: Test QuantitativeWorld.Text.Json
      run: dotnet test ./src/QuantitativeWorld.Text.Json.Tests/QuantitativeWorld.Text.Json.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=QuantitativeWorld.Text.Json.TestsResults.trx"
          
    - name: Test DecimalQuantitativeWorld
      run: dotnet test ./src/QuantitativeWorld.Tests/DecimalQuantitativeWorld.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=DecimalQuantitativeWorld.TestsResults.trx"
      
    - name: Test DecimalQuantitativeWorld.Text
      run: dotnet test ./src/QuantitativeWorld.Text.Tests/DecimalQuantitativeWorld.Text.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=DecimalQuantitativeWorld.Text.TestsResults.trx"
      
    - name: Test DecimalQuantitativeWorld.Text.Json
      run: dotnet test ./src/QuantitativeWorld.Text.Json.Tests/DecimalQuantitativeWorld.Text.Json.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=DecimalQuantitativeWorld.Text.Json.TestsResults.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v1
      with:
        name: tests
        path: ./tests
      
  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.event.release != null && github.event.action == 'published'
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build
    
    - name: Read GitVersion
      id: gitversion
      run: echo "::set-output name=semver::$(head -n 1 ./build/gitversion.semver.txt)"
      
    - name: Select packages to publish 
      run: |
        mkdir -p ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.${{ steps.gitversion.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.Text.${{ steps.gitversion.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.Text.Json.${{ steps.gitversion.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.FluentAssertions.${{ steps.gitversion.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.DecimalQuantitativeWorld.${{ steps.gitversion.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.DecimalQuantitativeWorld.Text.${{ steps.gitversion.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.DecimalQuantitativeWorld.Text.Json.${{ steps.gitversion.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.DecimalQuantitativeWorld.FluentAssertions.${{ steps.gitversion.outputs.SemVer }}.nupkg ./published
        ls ./published

    - name: Upload published packages
      uses: actions/upload-artifact@v1
      with:
        name: published
        path: ./published
        
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NMPW2H0J }}
        nuget-version: '5.x'
      
    - name: Publish QuantitativeWorld
      run: nuget push "./published/SoterDevelopment.QuantitativeWorld.${{ steps.gitversion.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate
        
    - name: Publish QuantitativeWorld.Text
      run: nuget push "./published/SoterDevelopment.QuantitativeWorld.Text.${{ steps.gitversion.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate
        
    - name: Publish QuantitativeWorld.Text.Json
      run: nuget push "./published/SoterDevelopment.QuantitativeWorld.Text.Json.${{ steps.gitversion.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate
        
    - name: Publish QuantitativeWorld.FluentAssertions
      run: nuget push "./published/SoterDevelopment.QuantitativeWorld.FluentAssertions.${{ steps.gitversion.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate
      
    - name: Publish DecimalQuantitativeWorld
      run: nuget push "./published/SoterDevelopment.DecimalQuantitativeWorld.${{ steps.gitversion.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate
        
    - name: Publish DecimalQuantitativeWorld.Text
      run: nuget push "./published/SoterDevelopment.DecimalQuantitativeWorld.Text.${{ steps.gitversion.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate
        
    - name: Publish DecimalQuantitativeWorld.Text.Json
      run: nuget push "./published/SoterDevelopment.DecimalQuantitativeWorld.Text.Json.${{ steps.gitversion.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate
        
    - name: Publish DecimalQuantitativeWorld.FluentAssertions
      run: nuget push "./published/SoterDevelopment.DecimalQuantitativeWorld.FluentAssertions.${{ steps.gitversion.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate
