name: Build, test and publish

on:
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      SemVer: ${{ steps.gitversion.outputs.SemVer }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Fetch repository
      run: git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
          versionSpec: '5.x'

    - name: Use GitVersion
      id: gitversion  # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.15

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build QuantitativeWorld
      run: dotnet build ./src/QuantitativeWorld/QuantitativeWorld.csproj --configuration Release --framework netstandard2.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Build QuantitativeWorld.Text
      run: dotnet build ./src/QuantitativeWorld.Text/QuantitativeWorld.Text.csproj --configuration Release --framework netstandard2.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Build QuantitativeWorld.Json
      run: dotnet build ./src/QuantitativeWorld.Json/QuantitativeWorld.Json.csproj --configuration Release --framework net6.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Build QuantitativeWorld.Json.Newtonsoft
      run: dotnet build ./src/QuantitativeWorld.Json.Newtonsoft/QuantitativeWorld.Json.Newtonsoft.csproj --configuration Release --framework netstandard2.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Build QuantitativeWorld.FluentAssertions
      run: dotnet build ./src/QuantitativeWorld.FluentAssertions/QuantitativeWorld.FluentAssertions.csproj --configuration Release --framework net6.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Build DecimalQuantitativeWorld
      run: dotnet build ./src/QuantitativeWorld/DecimalQuantitativeWorld.csproj --configuration Release --framework netstandard2.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Build DecimalQuantitativeWorld.Text
      run: dotnet build ./src/QuantitativeWorld.Text/DecimalQuantitativeWorld.Text.csproj --configuration Release --framework netstandard2.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Build DecimalQuantitativeWorld.Json
      run: dotnet build ./src/QuantitativeWorld.Json/DecimalQuantitativeWorld.Json.csproj --configuration Release --framework net6.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Build DecimalQuantitativeWorld.Json.Newtonsoft
      run: dotnet build ./src/QuantitativeWorld.Json.Newtonsoft/DecimalQuantitativeWorld.Json.Newtonsoft.csproj --configuration Release --framework netstandard2.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Build DecimalQuantitativeWorld.FluentAssertions
      run: dotnet build ./src/QuantitativeWorld.FluentAssertions/DecimalQuantitativeWorld.FluentAssertions.csproj --configuration Release --framework net6.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Fetch repository
      run: git fetch --prune

    - name: Test QuantitativeWorld
      run: dotnet test ./src/QuantitativeWorld.Tests/QuantitativeWorld.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=QuantitativeWorld.TestsResults.trx"

    - name: Test QuantitativeWorld.Text
      run: dotnet test ./src/QuantitativeWorld.Text.Tests/QuantitativeWorld.Text.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=QuantitativeWorld.Text.TestsResults.trx"

    - name: Test QuantitativeWorld.Json
      run: dotnet test ./src/QuantitativeWorld.Json.Tests/QuantitativeWorld.Json.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=QuantitativeWorld.Json.TestsResults.trx"

    - name: Test QuantitativeWorld.Json.Newtonsoft
      run: dotnet test ./src/QuantitativeWorld.Json.Newtonsoft.Tests/QuantitativeWorld.Json.Newtonsoft.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=QuantitativeWorld.Json.Newtonsoft.TestsResults.trx"

    - name: Test DecimalQuantitativeWorld
      run: dotnet test ./src/QuantitativeWorld.Tests/DecimalQuantitativeWorld.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=DecimalQuantitativeWorld.TestsResults.trx"

    - name: Test DecimalQuantitativeWorld.Text
      run: dotnet test ./src/QuantitativeWorld.Text.Tests/DecimalQuantitativeWorld.Text.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=DecimalQuantitativeWorld.Text.TestsResults.trx"

    - name: Test DecimalQuantitativeWorld.Json
      run: dotnet test ./src/QuantitativeWorld.Json.Tests/DecimalQuantitativeWorld.Json.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=DecimalQuantitativeWorld.Json.TestsResults.trx"

    - name: Test DecimalQuantitativeWorld.Json.Newtonsoft
      run: dotnet test ./src/QuantitativeWorld.Json.Newtonsoft.Tests/DecimalQuantitativeWorld.Json.Newtonsoft.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=DecimalQuantitativeWorld.Json.Newtonsoft.TestsResults.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v1
      with:
        name: tests
        path: ./tests

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.event.release != null && github.event.action == 'published'
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Select packages to publish
      run: |
        mkdir -p ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.Text.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.Text.Json.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.Json.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.Json.Newtonsoft.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.QuantitativeWorld.FluentAssertions.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.DecimalQuantitativeWorld.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.DecimalQuantitativeWorld.Text.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.DecimalQuantitativeWorld.Json.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.DecimalQuantitativeWorld.Json.Newtonsoft.${{ needs.build.outputs.SemVer }}.nupkg ./published
        cp ./build/SoterDevelopment.DecimalQuantitativeWorld.FluentAssertions.${{ needs.build.outputs.SemVer }}.nupkg ./published
        ls ./published

    - name: Upload published packages
      uses: actions/upload-artifact@v1
      with:
        name: published
        path: ./published

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NMPW2H0J }}
        nuget-version: '5.x'

    - name: Publish QuantitativeWorld
      run: nuget push "./published/SoterDevelopment.QuantitativeWorld.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate

    - name: Publish QuantitativeWorld.Text
      run: nuget push "./published/SoterDevelopment.QuantitativeWorld.Text.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate

    - name: Publish QuantitativeWorld.Json
      run: nuget push "./published/SoterDevelopment.QuantitativeWorld.Json.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate

    - name: Publish QuantitativeWorld.Json.Newtonsoft
      run: nuget push "./published/SoterDevelopment.QuantitativeWorld.Json.Newtonsoft.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate

    - name: Publish QuantitativeWorld.FluentAssertions
      run: nuget push "./published/SoterDevelopment.QuantitativeWorld.FluentAssertions.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate

    - name: Publish DecimalQuantitativeWorld
      run: nuget push "./published/SoterDevelopment.DecimalQuantitativeWorld.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate

    - name: Publish DecimalQuantitativeWorld.Text
      run: nuget push "./published/SoterDevelopment.DecimalQuantitativeWorld.Text.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate

    - name: Publish DecimalQuantitativeWorld.Json
      run: nuget push "./published/SoterDevelopment.DecimalQuantitativeWorld.Json.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate

    - name: Publish DecimalQuantitativeWorld.Json.Newtonsoft
      run: nuget push "./published/SoterDevelopment.DecimalQuantitativeWorld.Json.Newtonsoft.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate

    - name: Publish DecimalQuantitativeWorld.FluentAssertions
      run: nuget push "./published/SoterDevelopment.DecimalQuantitativeWorld.FluentAssertions.${{ needs.build.outputs.SemVer }}.nupkg" -source nuget.org -SkipDuplicate
